encoding: utf-8
name: Sarthak Bhagat
url: http://sarthak268.github.io
author:
  name: Sarthak Bhagat
  email: sarthakb@andrew.cmu.edu
description: MSR, CMU. 
permalink: /posts/:title/
include: ['_pages']
